### ISSUE TITLE
etcd data not persisted

### ISSUE THREAD

**Issue by antoineco** [runseb/machine#42]
etcd data is not persisted, as a result all the cluster config is lost as soon as Docker is restarted. This is an issue when the user wants to reconfigure the Docker daemon.

**Comment by sebgoa** [comment]
HI @antoineco thanks for the issue. Indeed it is not persisted. We use the single node docker k8s deployment mechanism.I don't think it is persisted even upstream.

But we will look into it. We could mount a host path to /etc/data (whatever that directory with the etcd data is).

**Comment by antoineco** [comment]
Oh, it is, at least with an emptyDir or it would be a disaster :)

May I send a PR with a host mount?

**Comment by sebgoa** [comment]
yes that would be great...
I will look at it anyway, but it might take couple days
