### ISSUE TITLE
Golang version needs updating and aurora drivers removed

### ISSUE THREAD

**Issue by koaps** [runseb/machine#58]
I'm interested in trying kmachine, but builds are failing, first because golang 1.5.1 is old and with latest it was still throwing an error during builds.

drivers/aurora/aurora.go:16:2: cannot find package "github.com/runseb/egoscale/src/egoscale" in any of:
	/go/src/github.com/docker/machine/vendor/github.com/runseb/egoscale/src/egoscale (vendor tree)
	/usr/local/go/src/github.com/runseb/egoscale/src/egoscale (from $GOROOT)
	/go/src/github.com/runseb/egoscale/src/egoscale (from $GOPATH)
mk/build.mk:22: recipe for target 'build-x-machine-driver-aurora' failed
make: *** [build-x-machine-driver-aurora] Error 1
make: *** [cross] Error 2

Looks like aurora driver is gone from docker-machine, so I removed the driver and ran the build ok

**Comment by sebgoa** [comment]
Hi @koaps thanks for your interest in kmachine. However the project is deprecated.

You should use:

https://github.com/kubernetes/minikube

or Docker for Desktop which now contains kubernetes as well:

https://blog.docker.com/2018/04/docker-desktop-certified-kubernetes/

**Comment by koaps** [comment]
Thanks, playing with Docker-for-MAC now, kinda wish kmachine was current so I could use the brew installed docker-machine instead of the dmg one.

thanks
